spring:
  datasource:
    url: jdbc:mysql://localhost:33006/media_chat_auth?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

